texas_leg_scraper:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'texas_bills.duckdb'
      schema: 'bills'
      extensions:
        - httpfs
        - parquet
      external_root: 'data/curated'