sources:
  rss:
    daily:
      bills_passed: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=todaysbillspassed
      bills_filed_senate: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=todaysfiledsenate
      bills_filed_house: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=todaysfiledhouse
      bill_analyses: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=todaysbillanalyses
      fiscal_notes: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=todaysfiscalnotes
      bill_text: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=todaysbilltext
    upcoming:
      calendar_senate: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=upcomingcalendarssenate
      calendar_house: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=upcomingcalendarshouse
      meetings_senate: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=upcomingmeetingssenate
      meetings_house: https://capitol.texas.gov/MyTLO/RSS/RSS.aspx?Type=upcomingmeetingshouse
  html:
    history: https://capitol.texas.gov/BillLookup/History.aspx #?LegSess=89R&Bill=SB1
    text: https://capitol.texas.gov/BillLookup/Text.aspx
    actions: https://capitol.texas.gov/BillLookup/Actions.aspx
    companions: https://capitol.texas.gov/BillLookup/Companions.aspx
    amendments: https://capitol.texas.gov/BillLookup/Amendments.aspx
    authors: https://capitol.texas.gov/BillLookup/Authors.aspx
    sponsors: https://capitol.texas.gov/BillLookup/Sponsors.aspx
    captions: https://capitol.texas.gov/BillLookup/Captions.aspx
    bill_stages: https://capitol.texas.gov/BillLookup/BillStages.aspx

info:
  LegSess: 89R
config:
  misses_allowed: 10
  google_sheets_id: 1mB-wBoFKuu4kS482Yc2FQn6kByDJi6uIgm7l09V_8PQ